---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: NodePort
  ports:
    - port: 11434
      targetPort: 11434
      nodePort: 30001
  selector:
    app: ollama

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama-container
          image: ollama/ollama:0.12.6
          ports:
            - containerPort: 11434
          volumeMounts:
            - mountPath: /root/.ollama
              name: ollama-model-cache
          resources:
            limits:
              memory: 2Gi
              cpu: 1
            requests:
              memory: 1Gi
              cpu: 0.5
      volumes:
        - name: ollama-model-cache
          persistentVolumeClaim:
            claimName: ollama-model-cache-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi